name: Prod CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_ENV: prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      APP_ENV: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Determine version number
        id: version
        uses: mathieudutour/github-tag-action@v5.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: "main"
          prerelease_branches: "dev"
          no_prefix: true
          tag_template: "v$VERSION"
          fail_on_no_tag: false
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}

      - name: Create .env file
        run: echo "APP_VERSION=${{ steps.version.outputs.VERSION }}" >> .env
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.APP_NAME }}:${{ steps.version.outputs.VERSION }}
          build-args: |
            APP_ENV=${{ env.APP_ENV }}
            APP_VERSION=${{ steps.version.outputs.VERSION }}
          
      # - name: Deploy to prod environment
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.PROD_SERVER_HOST }}
      #     username: ${{ secrets.PROD_SERVER_USERNAME }}
      #     key: ${{ secrets.PROD_SERVER_SSH_KEY }}
      #     script: |
      #       cd /home/ubuntu/myapp
      #       export APP_NAME=${{ env.APP_NAME }}
      #       docker-compose down
      #       docker-compose pull
      #       docker-compose up -d

      - name: Create GitHub release
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          release_name: Release ${{ steps.version.outputs.VERSION }}
          body: |
            Release ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
          target_commitish: main
